---
title: "DIC Blanks"
author: "Brett Longworth"
date: "3/12/2020"
output: html_document
---

What is the effect of using WS process blanks for correcting water secondaries? 

1. Extract DIC data by wheel.
2. Find WS blanks by wheel and average
3. Apply LBC using WS blanks
4. Compare with DIC corrected with HY blanks

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(amstools)
library(tidyverse)
library(here)
library(knitr)
library(odbc)
library(blanks)

options(digits = 5)
theme_set(theme_light())

con <- conNOSAMS()
standards <- getStdTable()

wstd <- getNorm(from = as.Date("2019-01-01"), 
                 recs = c(1082, 17185, 83028, 159579)) %>%
  mutate(process = purrr::map_chr(tp_num, amstools::getProcess, con),
         system = substr(wheel, 1, 5)) %>%
  filter(process == "WS") %>%
  left_join(select(standards, rec_num, fm_consensus))

write_csv(wstd, here("data/wstd.csv"))
write_csv(standards, here("data/standards.csv"))

wstd <- wstd2
wstd %>% 
        group_by(sample_name, rec_num, system) %>%
        summarize(Fm = mean(norm_ratio), N = n()) %>%
        arrange(rec_num)

ggplot(wstd, aes(norm_ratio)) +
  geom_histogram() +
  facet_grid(system ~ rec_num, scales = "free")
```

## First try LBC by simple overall WS blank means. 

Separate by system too.

```{r}
wstdsys <- wstd %>%
  group_by(system) %>%
      mutate(FmBlank = mean(norm_ratio[which(rec_num == 159579)]),
             FmBlankErr = sd(norm_ratio[which(rec_num == 159579)]), #use SNICSer error calc here
             FmLBC = doLBC(norm_ratio, FmBlank, 1.0398),
             FmLBCerr = doLBCerr(norm_ratio, FmBlank, 1.0398,
                                 pmax(int_err, ext_err), FmBlankErr))


wstd %>% 
        group_by(sample_name, rec_num, system) %>%
        summarize(NoBC = mean(norm_ratio), 
                  LBC = mean(FmLBC),
                  fm_corr = mean(fm_corr),
                  fm_consensus = mean(fm_consensus),
                  N = n()) %>%
        arrange(rec_num)

```

## Average blanks by wheel and normalize

```{r}
wstdwheel <- wstd %>%
  group_by(system) %>%
      mutate(FmBlank = mean(norm_ratio[which(rec_num == 159579)]),
             FmBlankErr = sd(norm_ratio[which(rec_num == 159579)]), #use SNICSer error calc here
             FmLBC = doLBC(norm_ratio, FmBlank, 1.0398),
             FmLBCerr = doLBCerr(norm_ratio, FmBlank, 1.0398,
                                 pmax(int_err, ext_err), FmBlankErr))

```

