---
title: "Bulb gas MBC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(amstools)
library(DBI)
library(here)
library(gt)
```

Get data for bulb OX-I normalizing standards for all wheels that have new MBC parameters in dc13_test.

```{r}
con <- conNOSAMS()
query <- "SELECT wheel, wheel_pos, target.tp_num, rec_num,
                         ss, sample_name, norm_method, sample_type, total_umols_co2,
                         sig_tot_umols, mass_cont, mass_cont_err, fm_cont, fm_cont_err,
                         norm_ratio, fm_corr, sig_fm_corr, lg_blk_fm, sig_lg_blk_fm,
                         fm_mb_corr, sig_fm_mb_corr 
                       FROM dc13_test
                       JOIN target ON dc13_test.tp_num = target.tp_num
                       JOIN snics_results ON dc13_test.tp_num = snics_results.tp_num
                      WHERE sample_type = 'S'"
data <- dbGetQuery(con, query) 
length(unique(data$wheel))
data <- data %>%
  mutate(mass = total_umols_co2 * 12.015,
         sig_mass = sig_tot_umols * 12.015)
```

Apply MBC

```{r}
data <- data %>% 
  mutate(fm_mb_corr_r = pmap_dbl(list(.$fm_corr, .$fm_cont, 
                                 .$mass, .$mass_cont), 
                            doMBC)) %>% 

mutate(sig_fm_mb_corr_r = pmap_dbl(list(.$fm_corr, .$fm_cont, 
                               .$mass, .$mass_cont, 
                               .$sig_fm_corr, .$fm_cont_err, 
                               .$sig_mass, .$mass_cont_err), 
                               doMBCerr)) %>% 
  filter(!is.na(fm_mb_corr_r),
         rec_num != 87012)
```

Summarize OX-I data

```{r}
data %>% 
  filter(norm_ratio > 1.03) %>%  
  summarize(across(c(norm_ratio, fm_corr, sig_fm_corr, fm_mb_corr_r, sig_fm_mb_corr_r), mean), n()) %>% 
  rename("Norm Fm" = norm_ratio, "LBC Fm" = fm_corr, "LBC Fm err" = sig_fm_corr, "MBC Fm" = fm_mb_corr_r, "MBC Fm err" = sig_fm_mb_corr_r, "N" = "n()") %>%
  gt %>% 
  tab_header(title = "Mean ratio and error for normalized and blank corrected GS OX-I")
```

Look at ratio vs mass

```{r}
data %>% 
  filter(norm_ratio > 1.03) %>%  
  pivot_longer(cols = c(norm_ratio, fm_mb_corr_r), names_to = "method", values_to = "Fm") %>%  
ggplot(aes(mass, Fm, color = method)) +
  geom_hline(yintercept = 1.0398) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point(shape = 1, size = 2) +
  labs(title = "MBC Fm of GS OX-I vs mass")
```

